# Welcome to Jekyll!
title: Sushovan Majhi
email: sushovan.majhi08@gmail.com
description: This is Sushovan Majhi's person homepage.
baseurl: ""
url: "https://www.smajhi.com"
github_username: sushovan4

# Build settings  
markdown: kramdown	
theme: minima		
plugins:		
  - jekyll-feed
  - jekyll-sitemap	

collections:
  topics:
    output: true
    
defaults:
  - scope:
      path: ""
      type: topics
    values:
      layout: topic
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Sushovan Majhi
      
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
