# Welcome to Jekyll!
title: Sushovan Majhi
email: sushovan.majhi08@gmail.com
description: This is Sushovan Majhi's person homepage.
baseurl: ""
url: "https://www.smajhi.com"
github_username: sushovan4

# Build settings  
markdown: kramdown	
theme: minima		
plugins:		
  - jekyll-feed
  - jekyll-sitemap	
collections:
  research-projects:
    output: true
  teaching:
    output: false
  coding-projects:
    output: false

defaults:
  - scope:
      path: ""
      type: "teaching"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "research-projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
  - scope:
      path: ""
      type: tag
    values:
      layout: "tag"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: Sushovan Majhi
      
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
